services:
  bot:
    image: f1-bot:v0.0.3
    restart: unless-stopped
    env_file: .env
    environment:
      F1BOT_SQLITE_PATH: /data/f1bot.db
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data:
