services:
  postgres:
    container_name: mango_pg
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: mango
      POSTGRES_USER: mango
      POSTGRES_PASSWORD: mango
    network_mode: host
    command: ["postgres", "-c", "port=31055"]
    volumes:
      - mango_pgdata:/var/lib/postgresql/data

volumes:
  mango_pgdata:
